version: 0.2
env:
  variables:
    INPUT_FILE: "serverless.yml"
    S3_BUCKET: "DrinkDish/"
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  build:
    commands:
      - aws cloudformation package --template $INPUT_FILE --s3-bucket $S3_BUCKET --output-template buildspec.yml
artifacts:
    files:
        - buildspec.yml
        - beta.json
